version: 0.2

phases:
  install:
    runtime-versions:
       python: 3.9
  pre_build:
    commands:
      - make install
  build:
    commands:
      - make lint
      - make format
      - make test